# ─────────────────────────────────────────────────────────────────────────────
# constants.jl — Public constants for YFinance.jl
# ─────────────────────────────────────────────────────────────────────────────

"""
    QUOTE_SUMMARY_ITEMS

Valid module names for [`quote_summary`](@ref).
"""
const QUOTE_SUMMARY_ITEMS = [
    "assetProfile",
    "balanceSheetHistory",
    "balanceSheetHistoryQuarterly",
    "calendarEvents",
    "cashflowStatementHistory",
    "cashflowStatementHistoryQuarterly",
    "defaultKeyStatistics",
    "earnings",
    "earningsHistory",
    "earningsTrend",
    "financialData",
    "fundOwnership",
    "fundPerformance",
    "fundProfile",
    "incomeStatementHistory",
    "incomeStatementHistoryQuarterly",
    "indexTrend",
    "industryTrend",
    "insiderHolders",
    "insiderTransactions",
    "institutionOwnership",
    "majorDirectHolders",
    "majorHoldersBreakdown",
    "netSharePurchaseActivity",
    "price",
    "quoteType",
    "recommendationTrend",
    "secFilings",
    "sectorTrend",
    "summaryDetail",
    "summaryProfile",
    "topHoldings",
    "upgradeDowngradeHistory"
]

"""
    FUNDAMENTAL_TYPES

Valid fundamental statement types and their sub-items, grouped by statement.
Keys: `"income_statement"`, `"balance_sheet"`, `"cash_flow"`, `"valuation"`.
"""
const FUNDAMENTAL_TYPES = OrderedDict(
    "income_statement" => [
        "Amortization", "AmortizationOfIntangiblesIncomeStatement",
        "AverageDilutionEarnings", "BasicAccountingChange", "BasicAverageShares",
        "BasicContinuousOperations", "BasicDiscontinuousOperations", "BasicEPS",
        "BasicEPSOtherGainsLosses", "BasicExtraordinary",
        "ContinuingAndDiscontinuedBasicEPS", "ContinuingAndDiscontinuedDilutedEPS",
        "CostOfRevenue", "DepletionIncomeStatement",
        "DepreciationAmortizationDepletionIncomeStatement",
        "DepreciationAndAmortizationInIncomeStatement", "DepreciationIncomeStatement",
        "DilutedAccountingChange", "DilutedAverageShares", "DilutedContinuousOperations",
        "DilutedDiscontinuousOperations", "DilutedEPS", "DilutedEPSOtherGainsLosses",
        "DilutedExtraordinary", "DilutedNIAvailtoComStockholders", "DividendPerShare",
        "EBIT", "EBITDA", "EarningsFromEquityInterest", "EarningsFromEquityInterestNetOfTax",
        "ExciseTaxes", "GainOnSaleOfBusiness", "GainOnSaleOfPPE", "GainOnSaleOfSecurity",
        "GeneralAndAdministrativeExpense", "GrossProfit", "ImpairmentOfCapitalAssets",
        "InsuranceAndClaims", "InterestExpense", "InterestExpenseNonOperating",
        "InterestIncome", "InterestIncomeNonOperating", "MinorityInterests", "NetIncome",
        "NetIncomeCommonStockholders", "NetIncomeContinuousOperations",
        "NetIncomeDiscontinuousOperations", "NetIncomeExtraordinary",
        "NetIncomeFromContinuingAndDiscontinuedOperation",
        "NetIncomeFromContinuingOperationNetMinorityInterest",
        "NetIncomeFromTaxLossCarryforward", "NetIncomeIncludingNoncontrollingInterests",
        "NetInterestIncome", "NetNonOperatingInterestIncomeExpense", "NormalizedBasicEPS",
        "NormalizedDilutedEPS", "NormalizedEBITDA", "NormalizedIncome", "OperatingExpense",
        "OperatingIncome", "OperatingRevenue", "OtherGandA", "OtherIncomeExpense",
        "OtherNonOperatingIncomeExpenses", "OtherOperatingExpenses", "OtherSpecialCharges",
        "OtherTaxes", "OtherunderPreferredStockDividend", "PreferredStockDividends",
        "PretaxIncome", "ProvisionForDoubtfulAccounts", "ReconciledCostOfRevenue",
        "ReconciledDepreciation", "RentAndLandingFees", "RentExpenseSupplemental",
        "ReportedNormalizedBasicEPS", "ReportedNormalizedDilutedEPS",
        "ResearchAndDevelopment", "RestructuringAndMergernAcquisition", "SalariesAndWages",
        "SecuritiesAmortization", "SellingAndMarketingExpense",
        "SellingGeneralAndAdministration", "SpecialIncomeCharges", "TaxEffectOfUnusualItems",
        "TaxLossCarryforwardBasicEPS", "TaxLossCarryforwardDilutedEPS", "TaxProvision",
        "TaxRateForCalcs", "TotalExpenses", "TotalOperatingIncomeAsReported",
        "TotalOtherFinanceCost", "TotalRevenue", "TotalUnusualItems",
        "TotalUnusualItemsExcludingGoodwill", "WriteOff",
    ],
    "balance_sheet" => [
        "AccountsPayable", "AccountsReceivable", "AccruedInterestReceivable",
        "AccumulatedDepreciation", "AdditionalPaidInCapital",
        "AllowanceForDoubtfulAccountsReceivable", "AssetsHeldForSaleCurrent",
        "AvailableForSaleSecurities", "BuildingsAndImprovements", "CapitalLeaseObligations",
        "CapitalStock", "CashAndCashEquivalents", "CashCashEquivalentsAndShortTermInvestments",
        "CashEquivalents", "CashFinancial", "CommercialPaper", "CommonStock",
        "CommonStockEquity", "ConstructionInProgress", "CurrentAccruedExpenses",
        "CurrentAssets", "CurrentCapitalLeaseObligation", "CurrentDebt",
        "CurrentDebtAndCapitalLeaseObligation", "CurrentDeferredAssets",
        "CurrentDeferredLiabilities", "CurrentDeferredRevenue", "CurrentDeferredTaxesAssets",
        "CurrentDeferredTaxesLiabilities", "CurrentLiabilities", "CurrentNotesPayable",
        "CurrentProvisions", "DefinedPensionBenefit", "DerivativeProductLiabilities",
        "DividendsPayable", "DuefromRelatedPartiesCurrent", "DuefromRelatedPartiesNonCurrent",
        "DuetoRelatedPartiesCurrent", "DuetoRelatedPartiesNonCurrent", "EmployeeBenefits",
        "FinancialAssets", "FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal",
        "FinishedGoods", "FixedAssetsRevaluationReserve",
        "ForeignCurrencyTranslationAdjustments", "GainsLossesNotAffectingRetainedEarnings",
        "GeneralPartnershipCapital", "Goodwill", "GoodwillAndOtherIntangibleAssets",
        "GrossAccountsReceivable", "GrossPPE", "HedgingAssetsCurrent",
        "HeldToMaturitySecurities", "IncomeTaxPayable", "InterestPayable",
        "InventoriesAdjustmentsAllowances", "Inventory", "InvestedCapital",
        "InvestmentProperties", "InvestmentinFinancialAssets", "InvestmentsAndAdvances",
        "InvestmentsInOtherVenturesUnderEquityMethod", "InvestmentsinAssociatesatCost",
        "InvestmentsinJointVenturesatCost", "InvestmentsinSubsidiariesatCost",
        "LandAndImprovements", "Leases", "LiabilitiesHeldforSaleNonCurrent",
        "LimitedPartnershipCapital", "LineOfCredit", "LoansReceivable",
        "LongTermCapitalLeaseObligation", "LongTermDebt",
        "LongTermDebtAndCapitalLeaseObligation", "LongTermEquityInvestment",
        "LongTermProvisions", "MachineryFurnitureEquipment", "MinimumPensionLiabilities",
        "MinorityInterest", "NetDebt", "NetPPE", "NetTangibleAssets",
        "NonCurrentAccountsReceivable", "NonCurrentAccruedExpenses",
        "NonCurrentDeferredAssets", "NonCurrentDeferredLiabilities",
        "NonCurrentDeferredRevenue", "NonCurrentDeferredTaxesAssets",
        "NonCurrentDeferredTaxesLiabilities", "NonCurrentNoteReceivables",
        "NonCurrentPensionAndOtherPostretirementBenefitPlans", "NonCurrentPrepaidAssets",
        "NotesReceivable", "OrdinarySharesNumber", "OtherCapitalStock",
        "OtherCurrentAssets", "OtherCurrentBorrowings", "OtherCurrentLiabilities",
        "OtherEquityAdjustments", "OtherEquityInterest", "OtherIntangibleAssets",
        "OtherInventories", "OtherInvestments", "OtherNonCurrentAssets",
        "OtherNonCurrentLiabilities", "OtherPayable", "OtherProperties",
        "OtherReceivables", "OtherShortTermInvestments", "Payables",
        "PayablesAndAccruedExpenses",
        "PensionandOtherPostRetirementBenefitPlansCurrent",
        "PreferredSecuritiesOutsideStockEquity", "PreferredSharesNumber",
        "PreferredStock", "PreferredStockEquity", "PrepaidAssets", "Properties",
        "RawMaterials", "Receivables", "ReceivablesAdjustmentsAllowances",
        "RestrictedCash", "RestrictedCommonStock", "RetainedEarnings", "ShareIssued",
        "StockholdersEquity", "TangibleBookValue", "TaxesReceivable", "TotalAssets",
        "TotalCapitalization", "TotalDebt", "TotalEquityGrossMinorityInterest",
        "TotalLiabilitiesNetMinorityInterest", "TotalNonCurrentAssets",
        "TotalNonCurrentLiabilitiesNetMinorityInterest", "TotalPartnershipCapital",
        "TotalTaxPayable", "TradeandOtherPayablesNonCurrent", "TradingSecurities",
        "TreasurySharesNumber", "TreasuryStock", "UnrealizedGainLoss", "WorkInProcess",
        "WorkingCapital",
    ],
    "cash_flow" => [
        "AdjustedGeographySegmentData", "AmortizationCashFlow",
        "AmortizationOfIntangibles", "AmortizationOfSecurities",
        "AssetImpairmentCharge", "BeginningCashPosition", "CapitalExpenditure",
        "CapitalExpenditureReported", "CashDividendsPaid",
        "CashFlowFromContinuingFinancingActivities",
        "CashFlowFromContinuingInvestingActivities",
        "CashFlowFromContinuingOperatingActivities",
        "CashFlowFromDiscontinuedOperation",
        "CashFlowsfromusedinOperatingActivitiesDirect",
        "CashFromDiscontinuedFinancingActivities",
        "CashFromDiscontinuedInvestingActivities",
        "CashFromDiscontinuedOperatingActivities", "ChangeInAccountPayable",
        "ChangeInAccruedExpense", "ChangeInCashSupplementalAsReported",
        "ChangeInDividendPayable", "ChangeInIncomeTaxPayable",
        "ChangeInInterestPayable", "ChangeInInventory", "ChangeInOtherCurrentAssets",
        "ChangeInOtherCurrentLiabilities", "ChangeInOtherWorkingCapital",
        "ChangeInPayable", "ChangeInPayablesAndAccruedExpense", "ChangeInPrepaidAssets",
        "ChangeInReceivables", "ChangeInTaxPayable", "ChangeInWorkingCapital",
        "ChangesInAccountReceivables", "ChangesInCash", "ClassesofCashPayments",
        "ClassesofCashReceiptsfromOperatingActivities", "CommonStockDividendPaid",
        "CommonStockIssuance", "CommonStockPayments", "DeferredIncomeTax",
        "DeferredTax", "Depletion", "Depreciation", "DepreciationAmortizationDepletion",
        "DepreciationAndAmortization", "DividendPaidCFO", "DividendReceivedCFO",
        "DividendsPaidDirect", "DividendsReceivedCFI", "DividendsReceivedDirect",
        "DomesticSales", "EarningsLossesFromEquityInvestments",
        "EffectOfExchangeRateChanges", "EndCashPosition",
        "ExcessTaxBenefitFromStockBasedCompensation", "FinancingCashFlow",
        "ForeignSales", "FreeCashFlow", "GainLossOnInvestmentSecurities",
        "GainLossOnSaleOfBusiness", "GainLossOnSaleOfPPE",
        "IncomeTaxPaidSupplementalData", "InterestPaidCFF", "InterestPaidCFO",
        "InterestPaidDirect", "InterestPaidSupplementalData", "InterestReceivedCFI",
        "InterestReceivedCFO", "InterestReceivedDirect", "InvestingCashFlow",
        "IssuanceOfCapitalStock", "IssuanceOfDebt", "LongTermDebtIssuance",
        "LongTermDebtPayments", "NetBusinessPurchaseAndSale", "NetCommonStockIssuance",
        "NetForeignCurrencyExchangeGainLoss", "NetIncome",
        "NetIncomeFromContinuingOperations", "NetIntangiblesPurchaseAndSale",
        "NetInvestmentPropertiesPurchaseAndSale", "NetInvestmentPurchaseAndSale",
        "NetIssuancePaymentsOfDebt", "NetLongTermDebtIssuance",
        "NetOtherFinancingCharges", "NetOtherInvestingChanges", "NetPPEPurchaseAndSale",
        "NetPreferredStockIssuance", "NetShortTermDebtIssuance", "OperatingCashFlow",
        "OperatingGainsLosses", "OtherCashAdjustmentInsideChangeinCash",
        "OtherCashAdjustmentOutsideChangeinCash",
        "OtherCashPaymentsfromOperatingActivities",
        "OtherCashReceiptsfromOperatingActivities", "OtherNonCashItems",
        "PaymentsonBehalfofEmployees", "PaymentstoSuppliersforGoodsandServices",
        "PensionAndEmployeeBenefitExpense", "PreferredStockDividendPaid",
        "PreferredStockIssuance", "PreferredStockPayments",
        "ProceedsFromStockOptionExercised", "ProvisionandWriteOffofAssets",
        "PurchaseOfBusiness", "PurchaseOfIntangibles", "PurchaseOfInvestment",
        "PurchaseOfInvestmentProperties", "PurchaseOfPPE", "ReceiptsfromCustomers",
        "ReceiptsfromGovernmentGrants", "RepaymentOfDebt", "RepurchaseOfCapitalStock",
        "SaleOfBusiness", "SaleOfIntangibles", "SaleOfInvestment",
        "SaleOfInvestmentProperties", "SaleOfPPE", "ShortTermDebtIssuance",
        "ShortTermDebtPayments", "StockBasedCompensation", "TaxesRefundPaid",
        "TaxesRefundPaidDirect", "UnrealizedGainLossOnInvestmentSecurities",
    ],
    "valuation" => [
        "ForwardPeRatio", "PsRatio", "PbRatio", "EnterprisesValueEBITDARatio",
        "EnterprisesValueRevenueRatio", "PeRatio", "MarketCap", "EnterpriseValue",
        "PegRatio",
    ]
)

"""
    FUNDAMENTAL_INTERVALS

Valid interval values for [`fundamentals`](@ref): `"annual"`, `"quarterly"`, `"monthly"`.
"""
const FUNDAMENTAL_INTERVALS = ["annual", "quarterly", "monthly"]
