const HEADERS = [
    Dict(
        "upgrade-insecure-requests"=>"1",
        "User-Agent"=>"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0",
        "accept"=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
        "sec-ch-ua"=>"\"Microsoft Edge\";v=\"120\", \"Chromium\";v=\"120\", \"Not=A?Brand\";v=\"99\"",
        "sec-ch-ua-mobile"=>"?0",
        "sec-ch-ua-platform"=>"\"Windows\"",
        "sec-fetch-site"=>"none",
        "sec-fetch-mode"=>"navigate",
        "sec-fetch-user"=>"?1",
        "accept-encoding"=>"gzip",
        "accept-language"=>"en-US,en;q=0.9",
    ),
    Dict(
        "upgrade-insecure-requests"=>"1",
        "User-Agent"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
        "accept"=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "sec-ch-ua"=>"\"Google Chrome\";v=\"121\", \"Chromium\";v=\"121\", \"Not=A?Brand\";v=\"99\"",
        "sec-ch-ua-mobile"=>"?0",
        "sec-ch-ua-platform"=>"\"macOS\"",
        "sec-fetch-site"=>"none",
        "sec-fetch-mode"=>"navigate",
        "sec-fetch-user"=>"?1",
        "accept-encoding"=>"gzip, deflate",
        "accept-language"=>"en-US,en;q=0.9",
    ),
    Dict(
        "upgrade-insecure-requests"=>"1",
        "User-Agent"=>"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "accept"=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "sec-ch-ua"=>"\"Google Chrome\";v=\"122\", \"Chromium\";v=\"122\", \"Not=A?Brand\";v=\"99\"",
        "sec-ch-ua-mobile"=>"?0",
        "sec-ch-ua-platform"=>"\"Linux\"",
        "sec-fetch-site"=>"none",
        "sec-fetch-mode"=>"navigate",
        "sec-fetch-user"=>"?1",
        "accept-encoding"=>"gzip, deflate",
        "accept-language"=>"en-US,en;q=0.9,es;q=0.8",
    ),
    Dict(
        "upgrade-insecure-requests"=>"1",
        "User-Agent"=>"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0",
        "accept"=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "sec-fetch-site"=>"none",
        "sec-fetch-mode"=>"navigate",
        "sec-fetch-user"=>"?1",
        "accept-encoding"=>"gzip, deflate",
        "accept-language"=>"en-US,en;q=0.5",
    ),
]
